package test.com.employee.model;

public interface EmployeeDB_postgres {
	
	String DRIVER_NAME = "org.postgresql.Driver";
	String URL = "jdbc:postgresql://localhost:5432/golfzon";
	String USER = "kosta";
	String PASSWORD = "hi123456";
	String SQL_SELECT_ALL = "SELECT * FROM EMPLOYEE ORDER BY NUM DESC";
	String SQL_INSERT = "INSERT INTO EMPLOYEE(NUM,FIRST_NAME,LAST_NAME,EMAIL,SALARY) VALUES(NEXTVAL('SEQ_EMPLOYEE'),?,?,?,?)";
	String SQL_UPDATE = "UPDATE EMPLOYEE SET FIRST_NAME=?,LAST_NAME=?,EMAIL=?, SALARY=? WHERE NUM=?";
	String SQL_DELETE = "DELETE FROM EMPLOYEE WHERE NUM=?";
	String SQL_SELECT_ONE = "SELECT * FROM EMPLOYEE WHERE NUM=?";
	String SQL_SEARCH_LIST_FIRSTNAME = "SELECT * FROM EMPLOYEE WHERE FRIST_NAME LIKE ? ORDER BY NUM DESC ";
	String SQL_SEARCH_LIST_LASTNAME = "SELECT * FROM EMPLOYEE WHERE LAST_NAME LIKE ? ORDER BY NUM DESC";
	String SQL_SEARCH_LIST_EMAIL = "SELECT * FROM EMPLOYEE WHERE EMAIL LIKE ? ORDER BY NUM DESC";
	String SQL_SEARCH_LIST_SALARY = "SELECT * FROM EMPLOYEE WHERE SALARY LIKE ? ORDER BY NUM DESC";

}
