package com.golfzonacademy.score.model;

public interface ScoreDB_postgres {

	String DRIVER_NAME = "org.postgresql.Driver";
	String URL = "jdbc:postgresql://localhost:5432/golfzon";
	String USER = "kosta";
	String PASSWORD = "hi123456";
	String SQL_SELECT_ALL = "SELECT * FROM SCORE ORDER BY NUM DESC";
	String SQL_INSERT = "INSERT INTO SCORE(NUM,KOR,ENG,MATH,NAME) VALUES(NEXTVAL('SEQ_SCORE'),?,?,?,?)";
	String SQL_UPDATE = "UPDATE SCORE SET NAME=?, KOR=?,ENG=?, MATH=? WHERE NUM=?";
	String SQL_DELETE = "DELETE FROM SCORE WHERE NUM=?";
	String SQL_SELECT_ONE = "SELECT * FROM SCORE WHERE NUM=?";
	String SQL_SEARCH_LIST_KOR = "SELECT * FROM SCORE WHERE KOR LIKE ? ORDER BY NUM DESC ";
	String SQL_SEARCH_LIST_ENG = "SELECT * FROM SCORE WHERE ENG LIKE ? ORDER BY NUM DESC";
	String SQL_SEARCH_LIST_NAME = "SELECT * FROM SCORE WHERE NAME LIKE ? ORDER BY NUM DESC";

}
