-- USER SQL
CREATE USER "KOSTA" IDENTIFIED BY "hi123456"  ;

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "KOSTA" ;
GRANT "RESOURCE" TO "KOSTA" ;

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "KOSTA" ;

ALTER USER "HR" IDENTIFIED BY "hi123456" 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

